---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: beanstalk-pv-volume
  labels:
    type: local
    app: beanstalk
spec:
  storageClassName: manual
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: beanstalk-pv-claim
  labels:
    app: beanstalk
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: beanstalk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: beanstalk
    spec:
      containers:
        - name: beanstalk
          image: schickling/beanstalkd
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 11300
          volumeMounts:
            - mountPath: /var/lib/beanstalkd
              name: beanstalk
      volumes:
        - name: beanstalk
          persistentVolumeClaim:
            claimName: beanstalk-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: beanstalk
  labels:
    app: beanstalk
spec:
  type: ClusterIP
  ports:
   - port: 11300
  selector:
   app: beanstalk