apiVersion: v1
kind: ConfigMap
metadata:
  name: auctionmanager-config
  labels:
    app: auctionmanager
data:
  ADMIN_TOKEN: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjUxODYyNTQzMjUsImlhdCI6MTU4NjI1NDMyNSwiaXNzIjoidXNlcm1hbmFnZXIiLCJuYmYiOjE1ODYyNTQzMjUsInVzZXJfaWQiOjIsImlzX2FkbWluIjp0cnVlfQ.Kxs-vJvxcmjqfwiJ9cWw42umbSWKTeHL2u7VWTRVRU6oc6cQguoN6dVoZwJW7Z4K67ItgqaIDzblaJ1yxtR6d9sEERXHptENoDn3mhQCtGG5zWIVtTEZgoaWuEMEDfsH5LXfij3XVxGdhD-_uZ4NMlgDAxMYDUBxo5lbMhAsvymjhi01NQxM0UDVFZ6LEfgQNNA2F1zlkon1tWEv5-56a2FD_DPVgaASl2Ky1pmnI0_y_VPMgJZeQx-s6KJr4WNwuEn_4VQem4mLenpCTBaPjC55BiG11pUpiAOQiv1eKJSjaRWjT22q2aU06dNJRA5RsrmjBYa6Ik-i7VLBXL50qQ
