apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scheduler
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scheduler
            image: scheduler
            imagePullPolicy: "IfNotPresent"
          restartPolicy: OnFailure